#!/usr/bin/env bash
# ==========================================================
# DebMenux - Service Install Script Template
# ==========================================================
# File: scripts/services/_template.sh
# Description: Copy this template to create a new service
#              install script. Replace all <PLACEHOLDERS>.
#
# Naming: scripts/services/<service_id>.sh
#         The filename (without .sh) must match the "id" field
#         in services.json.
#
# License: MIT
# ==========================================================

# ==============================================================================
# SERVICE METADATA
# ==============================================================================

APP="<Service Name>"           # Human-readable name (e.g. "AdGuard Home")
APP_ID="<service_id>"          # Lowercase ID, matches filename (e.g. "adguard")
CATEGORY="<category>"          # Category in services.json (e.g. "networking")
IMAGE="<image:tag>"            # Docker image (e.g. "adguard/adguardhome:latest")
PORT_WEB="${PORT_WEB:-<port>}" # Default web UI port (e.g. 3000)

# Resource defaults
var_cpu="${var_cpu:-1}"
var_ram="${var_ram:-512M}"

# Networks required (leave empty if none)
NETWORKS=()                    # e.g. ("iot_net" "db_net")

# ==============================================================================
# INSTALL FUNCTION (required)
# ==============================================================================

install_service() {
    local svc_dir="${DOCKER_DIR}/${APP_ID}"

    # ── Step 1: Create directories ────────────────────────────
    msg_info "Creating directories for ${APP}"
    mkdir -p "${svc_dir}/data"
    # Add more subdirectories as needed:
    # mkdir -p "${svc_dir}/data/config"
    # mkdir -p "${svc_dir}/data/logs"
    msg_ok "Directories created"

    # ── Step 2: Create networks (if needed) ───────────────────
    for net in "${NETWORKS[@]}"; do
        ensure_network "$net"
    done

    # ── Step 3: Generate .env file ────────────────────────────
    msg_info "Generating .env"
    cat > "${svc_dir}/.env" <<EOF
# ${APP} environment variables
# Generated by DebMenux on $(date -u +"%Y-%m-%d")
TZ=${TZ:-America/La_Paz}

# Add secrets here:
# EXAMPLE_PASSWORD=$(generate_password)
EOF
    secure_env "${svc_dir}/.env"
    msg_ok ".env created"

    # ── Step 4: Generate compose.yml ──────────────────────────
    msg_info "Generating compose.yml"
    cat > "${svc_dir}/compose.yml" <<EOF
# ${APP} — managed by DebMenux
services:
  ${APP_ID}:
    image: ${IMAGE}
    container_name: ${APP_ID}
    restart: unless-stopped
    env_file: .env
    ports:
      - "${PORT_WEB}:${PORT_WEB}"
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          cpus: '${var_cpu}'
          memory: ${var_ram}
    security_opt:
      - no-new-privileges:true
    cap_drop: [ALL]
    # cap_add: [CHOWN, DAC_OVERRIDE, SETUID, SETGID]  # Uncomment if needed
EOF
    msg_ok "compose.yml created"

    # ── Step 5: Set permissions ───────────────────────────────
    # chmod/chown AFTER files exist (never before mkdir)
    # Example: chown -R 1000:1000 "${svc_dir}/data"

    # ── Step 6: Start service ─────────────────────────────────
    msg_info "Starting ${APP}"
    docker compose -f "${svc_dir}/compose.yml" up -d
    msg_ok "${APP} started"

    # ── Step 7: Show access info ──────────────────────────────
    local server_ip
    server_ip=$(get_server_ip)

    echo -e ""
    msg_success "${APP} installed successfully!"
    echo -e "${TAB}${BOLD}Access:${CL} ${BL}http://${server_ip}:${PORT_WEB}${CL}"
    echo -e ""

    # ── Step 8: Register to external catalog (if integration enabled)
    register_to_catalog
}

# ==============================================================================
# UPDATE FUNCTION (optional — fallback is pull+recreate)
# ==============================================================================

update_service() {
    local svc_dir="${DOCKER_DIR}/${APP_ID}"

    if [[ ! -f "${svc_dir}/compose.yml" ]]; then
        msg_error "No ${APP} installation found!"
        return 1
    fi

    msg_info "Updating ${APP}"
    docker compose -f "${svc_dir}/compose.yml" pull
    docker compose -f "${svc_dir}/compose.yml" up -d --force-recreate
    msg_ok "${APP} updated"
}

# ==============================================================================
# UNINSTALL FUNCTION (optional)
# ==============================================================================

# uninstall_service() {
#     local svc_dir="${DOCKER_DIR}/${APP_ID}"
#     svc_down "$APP_ID"
#     echo -e "${TAB}${YWB}Data remains at: ${svc_dir}/data${CL}"
#     echo -e "${TAB}Remove manually with: rm -rf ${svc_dir}"
# }
