#!/usr/bin/env bash
# ==========================================================
# DebMenux - Service: EMQX
# ==========================================================
# Source: https://www.emqx.io/
# GitHub: https://github.com/emqx/emqx
# Description: High-performance MQTT broker for IoT
# License: MIT
# ==========================================================

# ==============================================================================
# SERVICE METADATA
# ==============================================================================

APP="EMQX"
APP_ID="emqx"
CATEGORY="iot"
IMAGE="emqx/emqx:5.8.3"
PORT_MQTT="${PORT_MQTT:-1883}"
PORT_MQTTS="${PORT_MQTTS:-8883}"
PORT_WS="${PORT_WS:-8083}"
PORT_WSS="${PORT_WSS:-8084}"
PORT_DASHBOARD="${PORT_DASHBOARD:-18083}"

# Resources
var_cpu="${var_cpu:-1}"
var_ram="${var_ram:-1G}"

# Networks
NETWORKS=("iot_net")

# ==============================================================================
# INSTALL
# ==============================================================================

install_service() {
    local svc_dir="${DOCKER_DIR}/${APP_ID}"

    # ── Step 1: Create directories ────────────────────────────
    msg_info "Creating directories"
    mkdir -p "${svc_dir}/data/data"
    mkdir -p "${svc_dir}/data/log"
    msg_ok "Directories created"

    # ── Step 2: Create networks ───────────────────────────────
    for net in "${NETWORKS[@]}"; do
        ensure_network "$net"
    done

    # ── Step 3: Generate secrets ──────────────────────────────
    msg_info "Generating secrets"
    local node_cookie
    local dashboard_pass
    node_cookie=$(generate_token 32)
    dashboard_pass=$(generate_password 18)

    cat > "${svc_dir}/.env" <<EOF
# EMQX environment variables
# Generated by DebMenux on $(date -u +"%Y-%m-%d")
TZ=${TZ:-America/La_Paz}

# Node cookie (cluster auth token)
EMQX_NODE_COOKIE=${node_cookie}

# Dashboard credentials
EMQX_DASHBOARD_USER=admin
EMQX_DASHBOARD_PASSWORD=${dashboard_pass}

# Security
EMQX_ALLOW_ANONYMOUS=false

# Ports (change here to remap)
EMQX_PORT_MQTT=${PORT_MQTT}
EMQX_PORT_MQTTS=${PORT_MQTTS}
EMQX_PORT_WS=${PORT_WS}
EMQX_PORT_WSS=${PORT_WSS}
EMQX_PORT_DASHBOARD=${PORT_DASHBOARD}
EOF
    secure_env "${svc_dir}/.env"
    msg_ok "Secrets generated"

    # ── Step 4: Generate compose.yml ──────────────────────────
    msg_info "Generating compose.yml"
    cat > "${svc_dir}/compose.yml" <<'EOF'
# EMQX MQTT Broker — managed by DebMenux
services:
  emqx:
    image: emqx/emqx:5.8.3
    container_name: emqx
    restart: unless-stopped
    env_file: .env
    environment:
      EMQX_NODE__NAME: "emqx@emqx.iot_net"
      EMQX_NODE__COOKIE: "${EMQX_NODE_COOKIE}"
      EMQX_NODE__ROLE: core
      EMQX_CLUSTER__DISCOVERY_STRATEGY: manual
      EMQX_DASHBOARD__DEFAULT_USERNAME: "${EMQX_DASHBOARD_USER}"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "${EMQX_DASHBOARD_PASSWORD}"
      EMQX_ALLOW_ANONYMOUS: "${EMQX_ALLOW_ANONYMOUS:-false}"
      EMQX_LOG__CONSOLE_HANDLER__LEVEL: warning
    ports:
      - "${EMQX_PORT_MQTT:-1883}:1883"
      - "${EMQX_PORT_MQTTS:-8883}:8883"
      - "${EMQX_PORT_WS:-8083}:8083"
      - "${EMQX_PORT_WSS:-8084}:8084"
      - "${EMQX_PORT_DASHBOARD:-18083}:18083"
    volumes:
      - ./data/data:/opt/emqx/data
      - ./data/log:/opt/emqx/log
    networks:
      - iot_net
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "emqx", "ctl", "status"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  iot_net:
    external: true
EOF
    msg_ok "compose.yml created"

    # ── Step 5: Start service ─────────────────────────────────
    msg_info "Starting ${APP}"
    docker compose -f "${svc_dir}/compose.yml" up -d
    msg_ok "${APP} started"

    # ── Step 6: Wait for healthy ──────────────────────────────
    msg_info "Waiting for ${APP} to be ready"
    local retries=0
    while [[ $retries -lt 15 ]]; do
        if docker exec emqx emqx ctl status 2>/dev/null | grep -q "is started"; then
            break
        fi
        sleep 2
        ((retries++))
    done

    if [[ $retries -ge 15 ]]; then
        msg_warn "${APP} is still starting... check logs with: docker logs emqx"
    else
        msg_ok "${APP} is ready"
    fi

    # ── Step 7: Show access info ──────────────────────────────
    local server_ip
    server_ip=$(get_server_ip)

    echo -e ""
    msg_success "${APP} installed successfully!"
    echo -e "${TAB}${BOLD}Dashboard:${CL}   ${BL}http://${server_ip}:${PORT_DASHBOARD}${CL}"
    echo -e "${TAB}${BOLD}MQTT:${CL}        ${server_ip}:${PORT_MQTT}"
    echo -e "${TAB}${BOLD}MQTT/TLS:${CL}    ${server_ip}:${PORT_MQTTS}"
    echo -e "${TAB}${BOLD}WebSocket:${CL}   ${server_ip}:${PORT_WS}"
    echo -e "${TAB}${BOLD}WSS:${CL}         ${server_ip}:${PORT_WSS}"
    echo -e ""
    echo -e "${TAB}${BOLD}Dashboard Login:${CL}"
    echo -e "${TAB}  User: ${GN}admin${CL}"
    echo -e "${TAB}  Pass: ${GN}${dashboard_pass}${CL}"
    echo -e ""
    echo -e "${TAB}${DIM}Credentials saved in: ${svc_dir}/.env${CL}"
    echo -e "${TAB}${DIM}Anonymous MQTT is DISABLED. Create users in the dashboard.${CL}"
    echo -e ""
}

# ==============================================================================
# UPDATE
# ==============================================================================

update_service() {
    local svc_dir="${DOCKER_DIR}/${APP_ID}"

    if [[ ! -f "${svc_dir}/compose.yml" ]]; then
        msg_error "No ${APP} installation found!"
        return 1
    fi

    msg_info "Pulling latest image"
    docker compose -f "${svc_dir}/compose.yml" pull
    msg_ok "Image updated"

    msg_info "Recreating container"
    docker compose -f "${svc_dir}/compose.yml" up -d --force-recreate
    msg_ok "${APP} updated"

    msg_warn "Note: Major version upgrades may require data migration."
    msg_warn "Check: https://www.emqx.io/docs/en/latest/changes/breaking-changes.html"
}
